// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package config

import (
	"github.com/APSN4/RAG-model-go/app/controller"
	"github.com/APSN4/RAG-model-go/app/repository"
	"github.com/APSN4/RAG-model-go/app/service"
	"github.com/google/wire"
)

// Injectors from injector.go:

func Init() *Initialization {
	gormDB := ConnectToDB()
	userRepositoryImpl := repository.UserRepositoryInit(gormDB)
	userServiceImpl := service.UserServiceInit(userRepositoryImpl)
	userControllerImpl := controller.UserControllerInit(userServiceImpl)
	roleRepositoryImpl := repository.RoleRepositoryInit(gormDB)
	gptServiceImpl := service.GPTServiceInit()
	gptControllerImpl := controller.GPTControllerInit(gptServiceImpl)
	limitServiceImpl := service.LimitServiceInit()
	limitControllerImpl := controller.LimitControllerInit(limitServiceImpl)
	changeAPIServiceImpl := service.ChangeAPIServiceInit()
	changeAPIControllerImpl := controller.ChangeAPIControllerInit(changeAPIServiceImpl)
	initialization := NewInitialization(userRepositoryImpl, userServiceImpl, userControllerImpl, roleRepositoryImpl, gptServiceImpl, gptControllerImpl, limitServiceImpl, limitControllerImpl, changeAPIControllerImpl, changeAPIServiceImpl)
	return initialization
}

// injector.go:

var db = wire.NewSet(ConnectToDB)

var userServiceSet = wire.NewSet(service.UserServiceInit, wire.Bind(new(service.UserService), new(*service.UserServiceImpl)))

var userRepoSet = wire.NewSet(repository.UserRepositoryInit, wire.Bind(new(repository.UserRepository), new(*repository.UserRepositoryImpl)))

var userCtrlSet = wire.NewSet(controller.UserControllerInit, wire.Bind(new(controller.UserController), new(*controller.UserControllerImpl)))

var roleRepoSet = wire.NewSet(repository.RoleRepositoryInit, wire.Bind(new(repository.RoleRepository), new(*repository.RoleRepositoryImpl)))

var GPTServiceSet = wire.NewSet(service.GPTServiceInit, wire.Bind(new(service.GPTService), new(*service.GPTServiceImpl)))

var GPTCtrlSet = wire.NewSet(controller.GPTControllerInit, wire.Bind(new(controller.GPTController), new(*controller.GPTControllerImpl)))

var LimitServiceSet = wire.NewSet(service.LimitServiceInit, wire.Bind(new(service.LimitService), new(*service.LimitServiceImpl)))

var LimitCtrlSet = wire.NewSet(controller.LimitControllerInit, wire.Bind(new(controller.LimitController), new(*controller.LimitControllerImpl)))

var ChangeAPIServiceSet = wire.NewSet(service.ChangeAPIServiceInit, wire.Bind(new(service.ChangeAPIService), new(*service.ChangeAPIServiceImpl)))

var ChangeAPICtrlSet = wire.NewSet(controller.ChangeAPIControllerInit, wire.Bind(new(controller.ChangeAPIController), new(*controller.ChangeAPIControllerImpl)))
